name: Daily Cold Plunge Reminder

# This workflow will run on a schedule
on:
  schedule:

    # questions - cron syntax- how do we define schedule, how do we
    # example of cron '0 13 * * *' is 8am est
    - cron: '0 8 * * *'
  # This allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch:

# A job is a set of steps that execute on the same runner
jobs:
  send_daily_email:
    runs-on: ubuntu-latest #other options?

  
    steps:
      # step 1 check out repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # step 2 python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # step 3 setup python libraries 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yagmail

      # step 4 run py script
      - name: Run email script
        run: python send_email.py
        env:
          # map gh secret to env variable in workflow 
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
